#!/usr/bin/env python3

from math import *
import sys

exp = ""
for a in sys.argv[1:]:
	exp += a

result = eval(exp)

print("result: ", result, sep="")
print("hex   : ", hex(int(result)), sep="")

binary = bin(int(result))[2:]
binary = "0" * (4 - len(binary) % 4) + binary
binary = " ".join(binary[::-1][i:i+4] for i in range(0, len(binary), 4))[::-1]
print("binary: ", binary, sep="")
